version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: ./docker/backend.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=luzian_db
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - postgres
    volumes:
      - ./backend/.env:/app/.env

  frontend:
    build:
      context: ..
      dockerfile: ./docker/frontend.Dockerfile
    ports:
      - "8080:5173"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=luzian_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: